version: '3'

services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    #network_mode: "host"
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - "9094:9094"
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    #network_mode: "host"
  kafdrop:
    image: 'docker.io/obsidiandynamics/kafdrop'
    ports:
      - '9000:9000'
    volumes: 
      - 'kafdrop_data:/kafdrop'
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
      #- KAFKA_BROKERCONNECT=localhost:9092
    depends_on:
        - kafka
    #network_mode: "host"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  kafdrop_data:
    driver: local